django/config/urls.py
from django.contrib import admin
from django.urls import path,include

import core.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core.urls, namespace='core')),
]

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('movies', views.MovieList.as_view(), name= 'MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
]

django/core/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated '),
        (RATED_G,'G - General Audiences'),
        (RATED_PG, 'PG - Parental Guidance'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(
        choices=RATINGS,
        default=NOT_RATED
    )
    runtime = models.PositiveIntegerField()
    website = models.URLField(
        blank=True)
    def __str__(self):
        return '{} ({})'.format(
            self.title,self.year)

django/core/views.py
from django.views.generic import ListView, DetailView

from core.models import Movie

class MovieList(ListView):
    model = Movie
class MovieDetail(DetailView):
    model = Movie

django/core/templates/core/movie_detail.html
{%extends 'base.html'%}

{% block title %}
{{ object.title }} - {{ block.super }}

{% endblock %}


{% block main %}
<h1>{{ object  }}</h1>
<p class="lead">
    {{ object.plot }}
</p>
{% endblock %}

{% block sidebar %}

<div>
 This movie is rated:
 <span class="badge badge-primary">
     {{ object.get_rating_display }}
 </span>

</div>

{% endblock %}

django/core/templates/core/movie_list.html
<!DOCTYPE html>
<html>
<body>
    <ul>
{% for movie in object_list %}
 <li>
     {{ movie }}
 </li>
{% empty %}

<li>
    No movies yet.
</li>
{% endfor %}


    </ul>
    <p>
        Using https?
        {{ request.is_secure| yesno }}
    </p>
</body>

</html>

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
     <meta charset="UTF-8">
     <meta
     name="viewport"
     content="width=device-width, initial-scale=1, shrink-to-fit=no"
     >
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
     <title>
         {% block title %} MyMDB {% endblock %}
     </title>
     <style>
     .mymdb-masthead {
         background-color: #eeeeee;
         margin-bottom: 1em;
         
     }
     </style>
    </head>
    <body>
        <div class="mymdb-masthead">
            <div class="container">
                <nav class="nav">
                    <div class="navbar-brand">MyMDB</div>
                    <a class="nav-link" href="{%url 'core:MovieList'%}">
                        Movies
                    </a>
                </nav>
            </div>

            <div class="container">
              <div class="row">
                  <div class="col-sm-8 mymdb-main">
                      {% block main%} {% endblock %}
                  </div>
                  <div
                  class="col-sm-3 offset-sm-1 mydb-sidebar">
                {% block sidebar %} {% endblock %}
                </div>
              

            </div>
        </div>
    </body>

</html>

django/templates/core/movie_list.html
<!DOCTYPE html>
<html>
<body>
    <ul>
{% for movie in object_list %}
 <li>
     {{ movie }}
 </li>
{% empty %}

<li>
    No movies yet.
</li>
{% endfor %}


    </ul>
    <p>
        Using https?
        {{ request.is_secure| yesno }}
    </p>
</body>

</html>